#!/bin/sh

set -e

case "$1" in
    configure)
        if ! getent passwd oprofile > /dev/null; then
            adduser --system --quiet \
                --home /var/lib/oprofile --no-create-home \
                --shell /bin/bash --group --gecos "OProfile JIT user" oprofile
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
